In [1]:
import os
from psm_final import EncodingModel, BetaVAEAnalysis, Algonauts, TripleN, shared_stimuli

import diffusers

ALGONAUTS_DIR = os.environ["ALGONAUTS_DIR"]
TRIPLE_N_DIR = os.environ["TRIPLE_N_DIR"]
NSD_MAT = "../nsd_expdesign.mat"

shared_ids = shared_stimuli(NSD_MAT)

ImportError: cannot import name 'EncodingModel' from 'psm_final' (/home/chuddy/dev/MCNB/PSM-NeuroAI-Final/src/psm_final/__init__.py)

In [2]:
algonauts = Algonauts(ALGONAUTS_DIR, shared_ids)
triple_n = TripleN(TRIPLE_N_DIR)
bvae_analysis = BetaVAEAnalysis(triple_n_path="/media/chuddy/Extreme SSD/data/triple-N/", model_path="../results/beta_vae/latent_512_beta_1.0_epochs_50_seed_42/vae.pth")

encoder = EncodingModel(analyzer=bvae_analysis)

In [3]:
encoder.encoding_triple_n(triple_n, algonauts, shared_ids)

            mean_encoding_score  std_encoding_score
area_label
Body                   0.109017            0.014030
Color                  0.189702            0.000000
Face                   0.025239            0.012500
Object                 0.081763            0.013429
Scene                  0.090030            0.014088
Unknown                0.087303            0.029482
V1                     0.238656            0.009302
V2                     0.173954            0.008063
V4                     0.116967            0.004749

In [3]:
encoder.encoding_algonauts(algonauts, triple_n, shared_ids)

             mean_encoding_score  std_encoding_score
roi
V1v                     0.215646            0.023224
V1d                     0.208346            0.058889
V2v                     0.166187            0.029131
V2d                     0.131621            0.025268
V3v                     0.107707            0.018560
V3d                     0.120162            0.021808
hV4                     0.100406            0.024577
EBA                     0.109246            0.036912
FBA-1                   0.088109            0.026939
FBA-2                   0.089036            0.045035
mTL-bodies              0.067482            0.030693
OFA                     0.052317            0.033240
FFA-1                   0.063617            0.035402
FFA-2                   0.064042            0.023795
OPA                     0.085083            0.043739
PPA                     0.109601            0.034568
RSC                     0.078473            0.042310
OWFA                    0.056304            0.036194
VWFA-1                  0.081488            0.044262
VWFA-2                  0.039228            0.061245
mfs-words               0.079765            0.038298
mTL-words               0.078438            0.071944
early                   0.126269            0.030227
midventral              0.088953            0.026818
midlateral              0.083152            0.016285
midparietal             0.068439            0.048113
ventral                 0.084679            0.025295
lateral                 0.106334            0.036526
parietal                0.061910            0.042081

In [3]:
tables = bvae_analysis.encoding_tables(
      algonauts,
      triple_n,
      shared_ids,
      regression="ridge",  # or "lasso"
      outer_folds=5,
      inner_folds=3,
  )

In [4]:
tables['algonauts']

,mean_encoding_score,std_encoding_score,best_alpha,alpha_selection_stability,outer_selected_alphas,n_targets,n_outer_folds
roi,,,,,,,
V1v,0.199737,0.012668,100.00,1.0,"100,100,100,100,100",9083,5
V1d,0.190593,0.013766,10.00,0.6,"10,10,10,100,100",12087,5
V2v,0.167279,0.015846,10.00,1.0,"10,10,10,10,10",10972,5
V2d,0.126170,0.017028,10.00,1.0,"10,10,10,10,10",10046,5
V3v,0.116871,0.015810,10.00,0.8,"1,10,10,10,10",8716,5
V3d,0.106462,0.016546,10.00,1.0,"10,10,10,10,10",9953,5
hV4,0.107034,0.014702,10.00,0.8,"1,10,10,10,10",8367,5
EBA,0.065521,0.014355,10.00,0.8,"10,10,100,10,10",58683,5
FBA-1,0.063833,0.010868,10.00,0.4,"10,10,100,100,100",6734,5
FBA-2,0.067845,0.010994,10.00,0.8,"10,10,100,10,10",8251,5
mTL-bodies,0.040318,0.021419,1000.00,0.2,"10000,1000,100,1,1",276,5
OFA,0.076170,0.013131,10.00,1.0,"10,10,10,10,10",8839,5
FFA-1,0.069556,0.015049,10.00,0.8,"10,10,10,10,1",8701,5
FFA-2,0.061969,0.014542,10.00,0.4,"10,10,100,1,1",6071,5
OPA,0.072655,0.012262,10.00,0.4,"10,100,100,100,10",30885,5
PPA,0.086116,0.026001,10.00,0.4,"10,100,100,100,10",22923,5
RSC,0.072078,0.026734,10.00,0.0,"100,100,1000,1000,100",9188,5
OWFA,0.053766,0.009700,10.00,0.6,"1,1,10,10,10",9991,5
VWFA-1,0.039560,0.010125,10.00,0.6,"10,10,100,100,10",10551,5
VWFA-2,0.046041,0.018566,10.00,0.4,"10,10,100,100,100",4714,5
mfs-words,0.049504,0.010714,10.00,0.4,"10,10,100,100,1",3895,5
mTL-words,0.041784,0.025695,0.01,0.0,"10,10,10,100,1",67,5
early,0.122618,0.011666,10.00,1.0,"10,10,10,10,10",83381,5
midventral,0.098866,0.013707,10.00,1.0,"10,10,10,10,10",15321,5
midlateral,0.059969,0.010318,10.00,0.6,"10,10,100,100,10",18291,5
midparietal,0.077252,0.008685,10.00,0.8,"10,10,10,100,10",15890,5
ventral,0.066141,0.014894,10.00,0.6,"10,10,100,100,10",78616,5
lateral,0.062643,0.012364,10.00,0.8,"10,10,100,10,10",53634,5
parietal,0.046178,0.011669,10.00,0.4,"10,100,100,1000,10",37278,5

In [5]:
tables['triple_n']

,mean_encoding_score,std_encoding_score,best_alpha,alpha_selection_stability,outer_selected_alphas,n_targets,n_outer_folds
area_label,,,,,,,
Body,0.093465,0.011787,10.0,0.8,"10,10,10,1,10",5015,5
Color,0.154901,0.003686,100.0,1.0,"100,100,100,100,100",1167,5
Face,0.093095,0.015324,1.0,0.6,"10,1,10,1,1",7479,5
Object,0.061193,0.003304,10.0,0.6,"10,1,10,1,10",4683,5
Scene,0.062281,0.003232,10.0,0.6,"10,100,100,10,10",3347,5
Unknown,0.077104,0.003700,10.0,0.8,"10,10,100,10,10",5967,5
V1,0.209322,0.014406,100.0,1.0,"100,100,100,100,100",2979,5
V2,0.147736,0.008360,10.0,0.2,"100,100,100,100,10",2738,5
V4,0.145631,0.007372,10.0,1.0,"10,10,10,10,10",3853,5